# Generated by Django 4.1.1 on 2022-10-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_imagee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gray', models.ImageField(upload_to='images')),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('medium', models.ImageField(upload_to='images')),
                ('large', models.ImageField(upload_to='images')),
                ('orignal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.imagee')),
            ],
        ),
    ]
